    steps:
    - name: 'gcr.io/cloud-builders/java/mvn'
      args: [ 'clean', 'package']
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/webapp-test:$REVISION_ID', '.' ]
    images:
    - 'gcr.io/$PROJECT_ID/webapp-test:$REVISION_ID'
